import { SoundDefinition, SoundId, MoodType, RoomThemeId } from './types';

export const SOUND_DEFINITIONS: SoundDefinition[] = [
  // --- Nature Group ---
  {
    id: 'rain',
    label: 'Rainfall',
    emoji: '🌧️',
    description: 'Soft continuous pink-filtered showers hitting window glass',
    category: 'nature',
  },
  {
    id: 'thunder',
    label: 'Distant Thunder',
    emoji: '⚡',
    description: 'Deep low-pass cloud rolls cracking every few minutes',
    category: 'nature',
  },
  {
    id: 'fireplace',
    label: 'Campfire',
    emoji: '🔥',
    description: 'Smoldering logs crackling with highpass-filtered snaps',
    category: 'nature',
  },
  {
    id: 'ocean',
    label: 'Ocean Breakers',
    emoji: '🌊',
    description: 'Heavy rhythmic coastal swells modulated by slow gain LFOs',
    category: 'nature',
  },
  {
    id: 'birds',
    label: 'Morning Birds',
    emoji: '🐦',
    description: 'Mellow chirping arrays generated by sine sweep arrays',
    category: 'nature',
  },

  // --- Urban Group ---
  {
    id: 'keyboard',
    label: 'Laptop Keyboard',
    emoji: '⌨️',
    description: 'Crisp, low-travel chiclet key taps mimicking focused office writing',
    category: 'urban',
  },
  {
    id: 'cafe',
    label: 'Café Corner',
    emoji: '☕',
    description: 'Low crowd chatter, coffee dripping, and muffled plate clinks',
    category: 'urban',
  },
  {
    id: 'city',
    label: 'Distant City',
    emoji: '🌆',
    description: 'Low drone of midnight traffic flow with distant soft sirens',
    category: 'urban',
  },
  {
    id: 'train',
    label: 'Night Train',
    emoji: '🚂',
    description: 'Rhythmic, low double-thump clackings of rail track shifts',
    category: 'urban',
  },

  // --- Noises Group ---
  {
    id: 'vinyl',
    label: 'Vinyl Static',
    emoji: '📻',
    description: 'Warm turntable surface crackle and micro needle pops',
    category: 'noise',
  },
  {
    id: 'white_noise',
    label: 'Pure Static',
    emoji: '🌫️',
    description: 'Bandpass-focused neutral white noise wash to mute distraction',
    category: 'noise',
  },

  // --- Music Group ---
  {
    id: 'soft_music',
    label: 'Ambient Pad',
    emoji: '🎹',
    description: 'Lush procedural synthesizer minor-eleventh pad progressions',
    category: 'music',
  }
];

export interface MoodMetadata {
  id: MoodType;
  label: string;
  emoji: string;
  tagline: string;
  accentColor: string;
}

export const MOODS: MoodMetadata[] = [
  {
    id: 'cozy',
    label: 'Cozy',
    emoji: '☕',
    tagline: 'nestled inside with warm lights',
    accentColor: 'from-amber-400 to-orange-500',
  },
  {
    id: 'studying',
    label: 'Studying',
    emoji: '📚',
    tagline: 'quietly focus-reading formulas',
    accentColor: 'from-teal-400 to-emerald-500',
  },
  {
    id: 'relaxing',
    label: 'Relaxing',
    emoji: '🍃',
    tagline: 'letting muscle tensions dissolve',
    accentColor: 'from-rose-400 to-pink-500',
  },
  {
    id: 'sleepy',
    label: 'Sleepy',
    emoji: '🌙',
    tagline: 'drifting in and out of consciousness',
    accentColor: 'from-indigo-400 to-purple-500',
  },
  {
    id: 'sad',
    label: 'Sad',
    emoji: '🌧️',
    tagline: 'staring at late night rain on windowpanes',
    accentColor: 'from-sky-400 to-blue-500',
  },
  {
    id: 'overthinking',
    label: 'Overthinking',
    emoji: '💭',
    tagline: 'disentangling complicated timelines',
    accentColor: 'from-violet-400 to-fuchsia-500',
  },
  {
    id: 'productive',
    label: 'Productive',
    emoji: '⚡',
    tagline: 'completing high-octane tasks successfully',
    accentColor: 'from-yellow-400 to-amber-500',
  },
  {
    id: 'lonely',
    label: 'Lonely',
    emoji: '🕯️',
    tagline: 'looking for digital presence in deep quiet',
    accentColor: 'from-slate-400 to-indigo-500',
  },
  {
    id: 'vibing',
    label: 'Vibing',
    emoji: '🎧',
    tagline: 'swaying to rhythmic soundwaves in dark rooms',
    accentColor: 'from-pink-400 to-rose-500',
  }
];

export interface ThemeVariables {
  accent: string;
  accentRgb: string;
  gradientStart: string;
  gradientEnd: string;
  cardBg: string;
  cardBorder: string;
  glow: string;
  textAccent: string;
  pulseSpeed: string;
}

export interface RoomThemeDefinition {
  id: RoomThemeId;
  label: string;
  emoji: string;
  description: string;
  dark: ThemeVariables;
  light: ThemeVariables;
}

export const ROOM_THEMES: RoomThemeDefinition[] = [
  {
    id: 'rainy',
    label: 'Rainy / Calm',
    emoji: '🌧️',
    description: 'Soft blue accents, cool gradients, and subtle glass reflections',
    dark: {
      accent: '#3b82f6',
      accentRgb: '59, 130, 246',
      gradientStart: '#080d1a',
      gradientEnd: '#0f172a',
      cardBg: 'rgba(15, 23, 42, 0.82)',
      cardBorder: 'rgba(59, 130, 246, 0.28)',
      glow: '0 8px 32px rgba(0, 0, 0, 0.4), 0 0 16px rgba(59, 130, 246, 0.15)',
      textAccent: '#60a5fa',
      pulseSpeed: '2.5s'
    },
    light: {
      accent: '#2563eb',
      accentRgb: '37, 99, 235',
      gradientStart: '#f0f9ff',
      gradientEnd: '#bae6fd',
      cardBg: 'rgba(255, 255, 255, 0.88)',
      cardBorder: 'rgba(37, 99, 235, 0.15)',
      glow: '0 8px 32px rgba(37, 99, 235, 0.08)',
      textAccent: '#1d4ed8',
      pulseSpeed: '2.5s'
    }
  },
  {
    id: 'cafe',
    label: 'Cozy Café',
    emoji: '☕',
    description: 'Warm amber tones, cream-colored cards, and comfortable soft lighting',
    dark: {
      accent: '#f59e0b',
      accentRgb: '245, 158, 11',
      gradientStart: '#140e0a',
      gradientEnd: '#29170d',
      cardBg: 'rgba(31, 21, 14, 0.85)',
      cardBorder: 'rgba(245, 158, 11, 0.25)',
      glow: '0 8px 32px rgba(0, 0, 0, 0.45), 0 0 16px rgba(245, 158, 11, 0.12)',
      textAccent: '#fbbf24',
      pulseSpeed: '3s'
    },
    light: {
      accent: '#d97706',
      accentRgb: '217, 119, 6',
      gradientStart: '#fffbeb',
      gradientEnd: '#fef3c7',
      cardBg: 'rgba(253, 251, 247, 0.92)',
      cardBorder: 'rgba(217, 119, 6, 0.12)',
      glow: '0 8px 32px rgba(217, 119, 6, 0.05)',
      textAccent: '#b45309',
      pulseSpeed: '3s'
    }
  },
  {
    id: 'latenight',
    label: 'Late Night',
    emoji: '🌌',
    description: 'Deep indigo and neon purple tones with low-light cinematic style',
    dark: {
      accent: '#a855f7',
      accentRgb: '168, 85, 247',
      gradientStart: '#02040e',
      gradientEnd: '#13112c',
      cardBg: 'rgba(17, 13, 33, 0.82)',
      cardBorder: 'rgba(168, 85, 247, 0.28)',
      glow: '0 8px 32px rgba(0, 0, 0, 0.5), 0 0 16px rgba(168, 85, 247, 0.15)',
      textAccent: '#c084fc',
      pulseSpeed: '3.5s'
    },
    light: {
      accent: '#7c3aed',
      accentRgb: '124, 58, 237',
      gradientStart: '#faf5ff',
      gradientEnd: '#e9d5ff',
      cardBg: 'rgba(255, 250, 255, 0.88)',
      cardBorder: 'rgba(124, 58, 237, 0.12)',
      glow: '0 8px 32px rgba(124, 58, 237, 0.05)',
      textAccent: '#6d28d9',
      pulseSpeed: '3.5s'
    }
  },
  {
    id: 'nature',
    label: 'Nature',
    emoji: '🌿',
    description: 'Green gradients, organic leaf tones, and earthy ambient glow',
    dark: {
      accent: '#10b981',
      accentRgb: '16, 185, 129',
      gradientStart: '#010f0b',
      gradientEnd: '#041f17',
      cardBg: 'rgba(8, 23, 18, 0.85)',
      cardBorder: 'rgba(16, 185, 129, 0.24)',
      glow: '0 8px 32px rgba(0, 0, 0, 0.45), 0 0 16px rgba(16, 185, 129, 0.12)',
      textAccent: '#34d399',
      pulseSpeed: '4s'
    },
    light: {
      accent: '#059669',
      accentRgb: '5, 150, 105',
      gradientStart: '#f0fdf4',
      gradientEnd: '#d1fae5',
      cardBg: 'rgba(244, 253, 247, 0.9)',
      cardBorder: 'rgba(5, 150, 105, 0.12)',
      glow: '0 8px 32px rgba(5, 150, 105, 0.05)',
      textAccent: '#047857',
      pulseSpeed: '4s'
    }
  },
  {
    id: 'storm',
    label: 'Storm',
    emoji: '⚡',
    description: 'Severe gray backdrop with neon electric blue highlights',
    dark: {
      accent: '#06b6d4',
      accentRgb: '6, 182, 212',
      gradientStart: '#04070d',
      gradientEnd: '#0d131f',
      cardBg: 'rgba(17, 24, 39, 0.88)',
      cardBorder: 'rgba(6, 182, 212, 0.3)',
      glow: '0 8px 32px rgba(0, 0, 0, 0.5), 0 0 18px rgba(6, 182, 212, 0.15)',
      textAccent: '#22d3ee',
      pulseSpeed: '1s'
    },
    light: {
      accent: '#0891b2',
      accentRgb: '8, 145, 178',
      gradientStart: '#f8fafc',
      gradientEnd: '#cbd5e1',
      cardBg: 'rgba(241, 245, 249, 0.92)',
      cardBorder: 'rgba(8, 145, 178, 0.15)',
      glow: '0 8px 32px rgba(8, 145, 178, 0.06)',
      textAccent: '#0e7490',
      pulseSpeed: '1.2s'
    }
  },
  {
    id: 'dreamy',
    label: 'Dreamy',
    emoji: '🌸',
    description: 'Soft lavender-pink dream clouds with beautiful warm transitions',
    dark: {
      accent: '#ec4899',
      accentRgb: '236, 72, 153',
      gradientStart: '#140816',
      gradientEnd: '#21082a',
      cardBg: 'rgba(28, 13, 34, 0.82)',
      cardBorder: 'rgba(236, 72, 153, 0.26)',
      glow: '0 8px 32px rgba(0, 0, 0, 0.42), 0 0 16px rgba(236, 72, 153, 0.12)',
      textAccent: '#f472b6',
      pulseSpeed: '5s'
    },
    light: {
      accent: '#db2777',
      accentRgb: '219, 39, 119',
      gradientStart: '#fdf2f8',
      gradientEnd: '#fce7f3',
      cardBg: 'rgba(255, 245, 248, 0.9)',
      cardBorder: 'rgba(219, 39, 119, 0.12)',
      glow: '0 8px 32px rgba(219, 39, 119, 0.05)',
      textAccent: '#be185d',
      pulseSpeed: '5s'
    }
  }
];

